Repository openelb/openelb, pull requests merged in 2019-03, with the labels that each got.

#20 Update README.md
  README.md
Labels: approved, lgtm

#23 Detect default interface and add e2e
  .gitignore
  Makefile
  cmd/manager/main.go
  config/agent/agent.yaml
  config/default/agent_image_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  hack/cleanup.sh
  hack/debug_in_cluster.sh
  hack/deploy.sh
  hack/e2e.sh
  hack/install_tools.sh
  hack/manager/debug_out_cluster.sh
  pkg/controller/eip/nettool/nettool.go
  pkg/controller/service/loadbalancer.go
  pkg/kubeutil/kubeutil.go
  pkg/util/ip.go
  pkg/util/ip_test.go
  pkg/util/string_test.go
  pkg/util/util_suite_test.go
  test/Jenkinsfile
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2eutil/e2eutil.go
  test/e2eutil/ssh.go
Labels: approved, enhancement, feature, lgtm, size/XL

#25 release v0.0.2
  CHANGELOG.md
  Makefile
  config/default/agent_image_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/S

#27 🚑we do not need to set externalIPs. fix #26
  .gitignore
  config/default/agent_image_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  pkg/controller/service/loadbalancer.go
  test/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#28 📖 update docs
  Makefile
  README.md
  doc/simulate_with_bird.md
Labels: approved, doc, lgtm, size/S

#29 ⛷modify jenkinsfile
  hack/e2e.sh
  pkg/controller/service/service_controller.go
  test/Jenkinsfile
Labels: approved, lgtm, size/M

#30 ✨release v0.0.3
  CHANGELOG.md
  Makefile
  config/default/agent_image_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/S

#35 Add more specific tests and fixes some bug
  Makefile
  config/bgp/config.toml
  config/default/agent_image_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  hack/e2e.sh
  pkg/controller/constant/constants.go
  pkg/controller/eip/eip_controller.go
  pkg/controller/eip/finalizer.go
  pkg/controller/service/finalizer.go
  pkg/controller/service/service_controller.go
  pkg/machinery/machinery_suite_test.go
  pkg/machinery/machinery_test.go
  pkg/machinery/requeue.go
  test/Jenkinsfile
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2eutil/clean.go
  test/e2eutil/e2eutil_suite_test.go
  test/e2eutil/e2eutil_test.go
  test/e2eutil/log.go
Labels: approved, enhancement, lgtm, size/L

#36 add doc about setting up in real router. fix #33
  doc/deploy_baremetal.md
  doc/router_config.md
Labels: approved, doc, lgtm, size/L

#38 🎉🎉 release v0.1
  CHANGELOG.md
  Makefile
  PROJECT
  config/default/agent_image_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  doc/bgp_config.md
Labels: approved, lgtm, size/S
