Repository openelb/openelb, pull requests merged in 2020-07, with the labels that each got.

#116 Update Porter comparison with MetalLB
  doc/compared_with_metallb.md
  doc/zh/compared_with_metallb.md
Labels: approved, lgtm, size/S

#115 add usecases.md and fix some typos
  doc/deploy_baremetal.md
  doc/eip_config.md
  doc/layer2.md
  doc/simulate_with_bird.md
  doc/usecases.md
  doc/zh/bgp_config.md
Labels: approved, lgtm, size/L

#117 refine Readme
  README.md
  doc/how-to-build.md
  doc/img/porter-logo.png
Labels: lgtm, size/M

#121 fix some typo and update README.md
  README.md
  doc/usecases.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
