Repository openelb/openelb, pull requests merged in 2020-06, with the labels that each got.

#102 refator ipam & layer2, and fix some bug
  Makefile
  api/v1alpha1/bgpconf_types.go
  api/v1alpha1/bgppeer_types.go
  api/v1alpha1/eip_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/bases/network.kubesphere.io_bgpconfs.yaml
  config/crd/bases/network.kubesphere.io_bgppeers.yaml
  config/crd/bases/network.kubesphere.io_eips.yaml
  config/workloads/manager.yaml
  controllers/bgp/bgpconf_controller.go
  controllers/bgp/bgppeer_controller.go
  controllers/lb/controller.go
  controllers/lb/lb.go
  controllers/lb/reconcile.go
  doc/layer2.md
  go.mod
  go.sum
  hack/test.sh
  pkg/bgp/serverd/bgp_test.go
  pkg/bgp/serverd/conf.go
  pkg/bgp/serverd/peers.go
  pkg/bgp/serverd/serverd.go
  pkg/errors/errors.go
  pkg/ipam/datastore.go
  pkg/ipam/eip_status.go
  pkg/ipam/ipam.go
  pkg/ipam/ipam_test.go
  pkg/ipam/protocol.go
  pkg/layer2/announcer.go
  pkg/layer2/announcer_test.go
  pkg/layer2/arp.go
  pkg/layer2/arp_test.go
  pkg/layer2/responder.go
  pkg/nettool/iptables.go
  test/Jenkinsfile
  test/docker/gobgp/Dockerfile
  test/docker/jenkins/Dockerfile
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2eutil/bgp.go
  test/e2eutil/clean.go
  test/e2eutil/e2eutil.go
  test/e2eutil/e2eutil_suite_test.go
  test/e2eutil/e2eutil_test.go
  test/e2eutil/log.go
  test/e2eutil/ssh.go
  test/e2eutil/test_case.go
  test/samples/bgpconf.yaml
  test/samples/bgppeer.yaml
  test/samples/eip.yaml
  test/samples/test.yaml
  test/test-configs/reciever.template
  test/test-configs/sender.template
Labels: approved, lgtm, size/XXL

#105 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/M

#103 Add Bird config doc in English
  README.md
  README_zh.md
  doc/deploy_baremetal.md
  doc/simulate_with_bird.md
  doc/zh/simulate_with_bird.md
Labels: approved, lgtm, size/L

#106 use cobra to implement command like k8s and update config file
  Makefile
  api/v1alpha1/bgpconf_types.go
  api/v1alpha1/bgppeer_types.go
  cmd/manager/app/manager.go
  cmd/manager/app/options/generic.go
  cmd/manager/app/options/options.go
  cmd/manager/main.go
  config/bgp/config.toml
  config/crd/bases/network.kubesphere.io_bgpconfs.yaml
  config/crd/bases/network.kubesphere.io_bgppeers.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/dev/kustomization.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/release/agent_image_patch.yaml
  config/release/manager_image_patch.yaml
  config/workloads/manager.yaml
  deploy/porter.yaml
  go.mod
  go.sum
  hack/agent/debug-out-of-cluster.sh
  hack/manager/debug_out_cluster.sh
  hack/manager/local_test.sh
  hack/test.sh
  pkg/bgp/serverd/options.go
  pkg/bgp/serverd/serverd.go
  pkg/log/log.go
Labels: approved, lgtm, size/XL

#109 Update network_v1alpha1_bgppeer.yaml
  config/samples/network_v1alpha1_bgppeer.yaml
Labels: approved, lgtm, size/XS

#110 Create porter-chart.md
  doc/zh/porter-chart.md
Labels: approved, lgtm, size/L
