Repository openelb/openelb, pull requests merged in 2020-05, with the labels that each got.

#83 Support spec.loadBalancerIP in service
  Makefile
  controllers/lb/lb.go
Labels: approved, lgtm, size/M

#86 doc: fix broken links in deploy_baremetal.md
  doc/deploy_baremetal.md
Labels: approved, lgtm, size/XS

#92 Support eip range
  api/v1alpha1/eip_types.go
  config/crd/bases/network.kubesphere.io_eips.yaml
  controllers/eip/eip_controller.go
  go.mod
  go.sum
  pkg/constant/constants.go
  pkg/ipam/datastore.go
  pkg/util/ip.go
  pkg/util/ip_test.go
Labels: approved, lgtm, size/L

#93 Add English docs
  doc/bgp_config.md
  doc/deploy_baremetal.md
  doc/router_config.md
  doc/zh/bgp_config.md
  doc/zh/compared_with_metallb.md
  doc/zh/deploy_baremetal.md
  doc/zh/router_config.md
  doc/zh/simulate_with_bird.md
  test/samples/eip.yaml
Labels: approved, lgtm, size/L

#97 Add copyright info
  LICENSE
Labels: approved, lgtm, size/XS
