Repository openelb/openelb, pull requests merged in 2021-01, with the labels that each got.

#140 Fix the broken links in the doc of simulate with bird
  doc/simulate_with_bird.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#142 Adapted to more layer2 and bgp scenes
  Dockerfile
  Makefile
  api/v1alpha2/bgpconf_types.go
  api/v1alpha2/bgppeer_types.go
  api/v1alpha2/eip_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/agent/Dockerfile
  cmd/manager/Dockerfile
  cmd/manager/app/manager.go
  cmd/manager/app/options/options.go
  config/crd/bases/network.kubesphere.io_bgpconfs.yaml
  config/crd/bases/network.kubesphere.io_bgppeers.yaml
  config/crd/bases/network.kubesphere.io_eips.yaml
  config/dev/manager_image_patch.yaml
  config/release/agent_image_patch.yaml
  config/release/manager_image_patch.yaml
  config/webhook/manifests.yaml
  config/workloads/manager.yaml
  deploy/porter.yaml
  doc/bgp_config.md
  doc/deploy.md
  go.mod
  go.sum
  pkg/constant/constants.go
  pkg/controllers/bgp/bgpconf_controller.go
  pkg/controllers/bgp/bgppeer_controller.go
  pkg/controllers/bgp/eventhandler.go
  pkg/controllers/bgp/suite_test.go
  pkg/controllers/ipam/ipam.go
  pkg/controllers/ipam/ipam_test.go
  pkg/controllers/lb/controller.go
  pkg/controllers/lb/eventhandler.go
  pkg/controllers/lb/suite_test.go
  pkg/leader-elector/election.go
  pkg/leader-elector/options.go
  pkg/manager/generic.go
  pkg/speaker/bgp/bgp_test.go
  pkg/speaker/bgp/conf.go
  pkg/speaker/bgp/options.go
  pkg/speaker/bgp/path.go
  pkg/speaker/bgp/peers.go
  pkg/speaker/layer2/arp.go
  pkg/speaker/layer2/arp_test.go
  pkg/speaker/speaker.go
  pkg/validate/validate.go
Labels: dco-signoff: yes, size/XXL

#143 Written install-porter-on-kubernetes-en.
  doc/deploy.md
  doc/img/install-porter-on-kubernetes/verify-porter-helm.jpg
  doc/img/install-porter-on-kubernetes/verify-porter-kubectl.jpg
  doc/install-porter-on-kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#146 Fixed issues based on comments.
  doc/img/install-porter-on-kubernetes/verify-porter-deletion-helm.jpg
  doc/img/install-porter-on-kubernetes/verify-porter-deletion-kubectl.jpg
  doc/install-porter-on-kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#147 Fixed minor issues.
  doc/install-porter-on-kubesphere.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#152 Written configure-ip-address-pools-using-eip-en
  doc/configure-ip-address-pools-using-eip.md
  doc/eip_config.md
Labels: approved, dco-signoff: yes, lgtm, size/L
