Repository openelb/openelb, pull requests merged in 2021-02, with the labels that each got.

#157 Written use-porter-in-layer-2-mode-en.
  doc/img/use-porter-in-layer-2-mode/ip-neigh.jpg
  doc/img/use-porter-in-layer-2-mode/node-ips.jpg
  doc/img/use-porter-in-layer-2-mode/pod-nodes.jpg
  doc/img/use-porter-in-layer-2-mode/service-cluster.jpg
  doc/img/use-porter-in-layer-2-mode/service-ip.jpg
  doc/img/use-porter-in-layer-2-mode/service-local.jpg
  doc/layer2.md
  doc/use-porter-in-layer-2-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#148 Written configure-porter-in-bgp-mode-en.
  doc/bgp-mode-network-topology.md
  doc/configure-porter-in-bgp-mode.md
  doc/img/bgp-mode-network-topology/porter-bgp-topology.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#162 Fixed minor issues.
  doc/configure-ip-address-pools-using-eip.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#161 Fixed minor issues.
  doc/install-porter-on-kubesphere.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#160 Fixed minor issues.
  doc/img/install-porter-on-kubernetes/verify-porter-deletion-helm.jpg
  doc/img/install-porter-on-kubernetes/verify-porter-deletion-kubectl.jpg
  doc/img/install-porter-on-kubernetes/verify-porter-helm.jpg
  doc/img/install-porter-on-kubernetes/verify-porter-kubectl.jpg
  doc/install-porter-on-kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#156 Written configure-porter-for-multi-router-clusters-en.
  doc/configure-porter-for-multi-router-clusters.md
  doc/img/configure-porter-for-multi-router-clusters/multi-router-topology-1.jpg
  doc/img/configure-porter-for-multi-router-clusters/multi-router-topology-2.jpg
  doc/img/configure-porter-for-multi-router-clusters/verify-configuration-result.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#159 Changed the service description.
  doc/use-porter-in-layer-2-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#158 Written use-porter-in-bgp-mode-en.
  doc/compared_with_metallb.md
  doc/img/use-porter-in-bgp-mode/access-service.jpg
  doc/img/use-porter-in-bgp-mode/bgp-routes-cluster.jpg
  doc/img/use-porter-in-bgp-mode/bgp-routes-local.jpg
  doc/img/use-porter-in-bgp-mode/bird-status.jpg
  doc/img/use-porter-in-bgp-mode/node-ips.jpg
  doc/img/use-porter-in-bgp-mode/service-ip.jpg
  doc/simulate_with_bird.md
  doc/usage.md
  doc/use-porter-in-bgp-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#164 Written index-en.
  doc/index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#163 Written layer-2-mode-network-topology-en.
  doc/bgp_config.md
  doc/img/layer-2-mode-network-topology/porter-layer-2-topology.jpg
  doc/layer-2-mode-network-topology.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#171 Fixed minor issues.
  doc/configure-porter-in-bgp-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#170 Fixed minor issues.
  doc/layer-2-mode-network-topology.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#169 Fixed minor issues.
  doc/configure-porter-for-multi-router-clusters.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#172 Fixed minor issues.
  doc/use-porter-in-bgp-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#173 Fixed minor issues.
  doc/use-porter-in-layer-2-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#153 filter endpoints not owned by service
  pkg/controllers/ipam/ipam.go
  pkg/controllers/lb/controller.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#167 Rewite how-to-build guide
  doc/how-to-build.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#168 Written configure-multiple-porter-replicas-en.
  doc/configure-multiple-porter-replicas.md
  doc/index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#175 Changed the doc name to bgp-mode-en.
  doc/bgp-mode.md
  doc/img/bgp-mode/porter-bgp-topology.jpg
Labels: approved, dco-signoff: yes, lgtm, size/XS

#177 Changed the doc name to layer-2-mode-en.
  doc/img/layer-2-mode/porter-layer-2-topology.jpg
  doc/index.md
  doc/layer-2-mode.md
  doc/use-porter-in-layer-2-mode.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#178 Written how-to-build-en.
  doc/how-to-build.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#179 Fixed minor issues.
  doc/configure-multiple-porter-replicas.md
  doc/configure-porter-for-multi-router-clusters.md
  doc/how-to-build.md
  doc/img/configure-multiple-porter-replicas/multi-router-topology-1.jpg
  doc/img/configure-multiple-porter-replicas/multi-router-topology-2.jpg
  doc/img/configure-multiple-porter-replicas/verify-configuration-result.jpg
Labels: approved, dco-signoff: yes, lgtm, size/XS

#181 Fixed minor issues.
  doc/configure-ip-address-pools-using-eip.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#182 Added a notice.
  doc/install-porter-on-kubesphere.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#165 Written readme-en.
  README.md
  README_zh.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#184 Added a note.
  doc/install-porter-on-kubesphere.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#185 Fixed minor issues.
  doc/configure-ip-address-pools-using-eip.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#183 Added a note.
  doc/install-porter-on-kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#186 Redirected links to porterlb.io.
  README.md
Labels: dco-signoff: yes, lgtm, size/XS
