Repository openelb/openelb, pull requests merged in 2022-08, with the labels that each got.

#301 allow endpoint nodeName to be empty
  pkg/controllers/lb/controller.go
  pkg/controllers/lb/suite_test.go
Labels: lgtm, approved, size/M

#303 add CIDR range for NICs in layer2
  pkg/speaker/layer2/arp.go
  pkg/speaker/layer2/arp_test.go
Labels: lgtm, approved, size/S

#292 feat(bgp): add method to configure BGP policies
  api/v1alpha2/bgpconf_types.go
  config/crd/bases/network.kubesphere.io_bgpconfs.yaml
  config/rbac/role.yaml
  config/release/agent_image_patch.yaml
  config/release/manager_image_patch.yaml
  deploy/openelb.yaml
  go.mod
  pkg/constant/constant.go
  pkg/controllers/bgp/bgpconf_controller.go
  pkg/speaker/bgp/bgp_test.go
  pkg/speaker/bgp/conf.go
  pkg/speaker/bgp/config/bgp_configs.go
  pkg/speaker/bgp/config/serve.go
  pkg/speaker/bgp/config/util.go
  pkg/speaker/bgp/peers.go
  pkg/speaker/bgp/policy.go
  pkg/speaker/bgp/table/table.go
Labels: lgtm, approved, size/XXL
