Repository openelb/openelb, pull requests merged in 2022-05, with the labels that each got.

#261 add all contributors
  .all-contributorsrc
  README.md
Labels: lgtm, approved, size/L

#265 fix detect keepalived daemonset
  pkg/speaker/vip/keepalived.go
Labels: lgtm, approved, size/M

#268 Update OWNERS
  OWNERS
Labels: approved, size/S

#273 update openelb image tag for next version
  deploy/openelb.yaml
Labels: lgtm, approved, size/XS

#274 ench: update readme
  README.md
  README_zh.md
Labels: lgtm, approved, size/S

#276 add uninstall script
  deploy/uninstall.sh
Labels: lgtm, approved, size/M

#275 Update roadmap
  doc/roadmap.md
Labels: lgtm, approved, size/M

#279 ench: add github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: lgtm, approved, size/M
