Repository openelb/openelb, pull requests merged in 2022-07, with the labels that each got.

#282 feat: add CIDR range for NICs in `layer2`
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  pkg/speaker/layer2/arp.go
  pkg/speaker/layer2/arp_test.go
  pkg/util/util.go
Labels: lgtm, approved, size/M

#293 feat(metrics):add some metrics
  VERSION
  cmd/manager/app/manager.go
  config/default/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/workloads/manager.yaml
  deploy/openelb.yaml
  go.mod
  go.sum
  pkg/controllers/bgp/bgppeer_controller.go
  pkg/controllers/bgp/suite_test.go
  pkg/controllers/ipam/ipam.go
  pkg/controllers/lb/suite_test.go
  pkg/manager/generic.go
  pkg/metrics/metrics.go
  pkg/speaker/bgp/path.go
  pkg/speaker/bgp/peers.go
  pkg/speaker/layer2/arp.go
Labels: lgtm, approved, size/XL

#297 Fix readme file
  README.md
  README_zh.md
Labels: lgtm, approved, size/XS

#285 Support config for container image
  cmd/manager/app/manager.go
  pkg/constant/constant.go
  pkg/controllers/lb/nodeproxy.go
  pkg/manager/generic.go
  pkg/speaker/vip/keepalived.go
Labels: lgtm, approved, size/M

#299 Update for next version
  VERSION
  deploy/openelb.yaml
Labels: lgtm, approved, size/XS

#298 Add version info
  Makefile
  cmd/manager/app/manager.go
  pkg/manager/generic.go
  pkg/version/version.go
Labels: lgtm, approved, size/M
