Repository openelb/openelb, pull requests merged in 2023-08, with the labels that each got.

#350 chore: integrate e2e test into the workflow
  .github/workflows/go.yml
  Makefile
  hack/deploy_openelb.sh
  hack/kind_e2e.sh
Labels: lgtm, approved, size/M

#348 remove default eip webhook
  cmd/controller/app/manager.go
  config/crd/bases/manifests.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/mutating_webhook.yaml
  config/workloads/cert.yaml
  deploy/openelb.yaml
  pkg/controllers/lb/controller.go
Labels: lgtm, approved, size/L

#349 fix: upgrade controller-gen
  Makefile
  config/crd/bases/manifests.yaml
  config/crd/bases/network.kubesphere.io_bgpconfs.yaml
  config/crd/bases/network.kubesphere.io_bgppeers.yaml
  config/crd/bases/network.kubesphere.io_eips.yaml
  config/crd/bases/role.yaml
  config/dev/kustomization.yaml
  config/rbac/role.yaml
  config/release/kustomization.yaml
  config/webhook/manifests.yaml
  deploy/openelb.yaml
Labels: lgtm, approved, size/L

#352 allocate eip to specified namespace
  api/v1alpha2/eip_types.go
  api/v1alpha2/types_test.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/network.kubesphere.io_bgpconfs.yaml
  config/crd/bases/network.kubesphere.io_bgppeers.yaml
  config/crd/bases/network.kubesphere.io_eips.yaml
  config/crd/bases/role.yaml
  deploy/openelb.yaml
  pkg/controllers/ipam/ipam.go
  pkg/controllers/ipam/ipam_test.go
  pkg/controllers/lb/controller.go
  pkg/speaker/manager.go
Labels: lgtm, approved, size/XL
