Repository openelb/openelb, pull requests merged in 2024-07, with the labels that each got.

#442 Add test for IPv6 allocation by IPAM
  pkg/controllers/ipam/ipamv6_test.go
Labels: lgtm, approved, size/XXL

#443 Remove the resolveIP of arp_announcer
  go.mod
  go.sum
  pkg/speaker/layer2/arp_announcer.go
Labels: lgtm, approved, size/M

#445 Add NDP announcer for layer2-speaker
  go.mod
  go.sum
  pkg/speaker/layer2/announcer.go
  pkg/speaker/layer2/arp_announcer.go
  pkg/speaker/layer2/const.go
  pkg/speaker/layer2/memberlist.go
  pkg/speaker/layer2/ndp_announcer.go
  pkg/speaker/utils.go
  pkg/speaker/vip/keepalived.go
Labels: lgtm, approved, size/L

#446 Bug fix
  pkg/speaker/layer2/memberlist.go
Labels: lgtm, approved, size/XS

#447 remove duplicate entries
  charts/templates/openelb-controller.yaml
Labels: approved, size/XS
