Repository openelb/openelb, pull requests merged in 2024-06, with the labels that each got.

#422 update charts & update changelog
  CHANGELOG.md
  charts/templates/openelb-images-configmap.yaml
  charts/templates/openelb-speaker.yaml
Labels: lgtm, approved, size/M

#424 fix iprange cidr parsing results
  pkg/util/iprange/parse.go
  pkg/util/iprange/parse_test.go
  pkg/util/iprange/range_test.go
Labels: lgtm, approved, size/M

#427 fix: ipam specify a different IP
  pkg/controllers/ipam/ipam.go
  pkg/controllers/ipam/ipam_test.go
Labels: lgtm, approved, size/S

#434 skip existing records when handling service
  pkg/speaker/manager.go
Labels: lgtm, approved, size/XS

#435 update charts
  charts/README.md
  charts/templates/openelb-controller.yaml
  charts/templates/openelb-secret.yaml
  charts/templates/openelb-speaker.yaml
  charts/values.yaml
  config/workloads/controller.yaml
  config/workloads/speaker.yaml
  deploy/openelb.yaml
Labels: lgtm, approved, size/L

#433 update charts
  README.md
  README_zh.md
  charts/README.md
  charts/templates/openelb-controller.yaml
  charts/templates/openelb-secret.yaml
  charts/templates/openelb-speaker.yaml
  charts/values.yaml
  openelb-0.6.0.tgz
Labels: lgtm, size/L

#431 determine if the speaker is registered
  pkg/speaker/manager.go
Labels: lgtm, approved, size/XS

#432 delete a single record instead of the entire instance
  pkg/speaker/vip/keepalived.go
Labels: lgtm, approved, size/XS

#437 update charts tag for release 0.6.0
  openelb-0.6.0.tgz
Labels: size/XS

#436 update images tag
  charts/values.yaml
  config/release/manager_image_patch.yaml
  config/release/speaker_image_patch.yaml
  deploy/openelb.yaml
Labels: approved, size/S

#439 update github workflow
  .github/workflows/docker.yml
Labels: lgtm, approved, size/L

#440 doc fix for old hardcoded github pages url
  README.md
  README_zh.md
  charts/README.md
Labels: lgtm, approved, size/S
